# Generated by Django 5.0.1 on 2024-02-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StreamVideo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
